ALTER TABLE venues ADD COLUMN IF NOT EXISTS region VARCHAR(100);
ALTER TABLE venues ADD COLUMN IF NOT EXISTS price_info VARCHAR(500);
ALTER TABLE venues ADD COLUMN IF NOT EXISTS line_at VARCHAR(200);
ALTER TABLE venues ADD COLUMN IF NOT EXISTS portaly_category VARCHAR(50);
ALTER TABLE venues ADD COLUMN IF NOT EXISTS booking_url VARCHAR(500);

ALTER TABLE facilitators ADD COLUMN IF NOT EXISTS region VARCHAR(100);
ALTER TABLE facilitators ADD COLUMN IF NOT EXISTS price_info VARCHAR(500);
ALTER TABLE facilitators ADD COLUMN IF NOT EXISTS line_at VARCHAR(200);
ALTER TABLE facilitators ADD COLUMN IF NOT EXISTS portaly_category VARCHAR(50);
ALTER TABLE facilitators ADD COLUMN IF NOT EXISTS booking_url VARCHAR(500);

ALTER TABLE herbals ADD COLUMN IF NOT EXISTS price_info VARCHAR(500);
ALTER TABLE herbals ADD COLUMN IF NOT EXISTS portaly_category VARCHAR(50);
ALTER TABLE herbals ADD COLUMN IF NOT EXISTS booking_url VARCHAR(500);

ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS price_info VARCHAR(500);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS portaly_category VARCHAR(50);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS booking_url VARCHAR(500);
