ALTER TABLE venues ADD COLUMN IF NOT EXISTS has_mirror BOOLEAN DEFAULT false;
ALTER TABLE venues ADD COLUMN IF NOT EXISTS has_wooden_floor BOOLEAN DEFAULT false;
ALTER TABLE venues ADD COLUMN IF NOT EXISTS has_accessibility BOOLEAN DEFAULT false;
ALTER TABLE venues ADD COLUMN IF NOT EXISTS has_audio_equipment BOOLEAN DEFAULT false;
ALTER TABLE venues ADD COLUMN IF NOT EXISTS has_parking BOOLEAN DEFAULT false;
ALTER TABLE venues ADD COLUMN IF NOT EXISTS has_shower BOOLEAN DEFAULT false;
ALTER TABLE venues ADD COLUMN IF NOT EXISTS has_kitchen BOOLEAN DEFAULT false;
ALTER TABLE venues ADD COLUMN IF NOT EXISTS has_wifi BOOLEAN DEFAULT false;
ALTER TABLE venues ADD COLUMN IF NOT EXISTS capacity INTEGER;
